USE ROLE ACCOUNTADMIN;

-- Route model calls to a Cortex-enabled region if yours doesn't host them natively.
ALTER ACCOUNT SET CORTEX_ENABLED_CROSS_REGION = 'ANY_REGION';

-- Compute
CREATE WAREHOUSE IF NOT EXISTS WALMART_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Compute for the Walmart forecasting + agent demo';

USE WAREHOUSE WALMART_WH;

CREATE DATABASE IF NOT EXISTS WALMART_DEMO;
USE DATABASE WALMART_DEMO;
CREATE SCHEMA IF NOT EXISTS FORECAST;
USE SCHEMA FORECAST;


SELECT SNOWFLAKE.CORTEX.COMPLETE('claude-4-sonnet', 'Reply with one word: ready') AS cortex_check;


-- CREATE API INTEGRATION IF NOT EXISTS GITHUB_INTEGRATION
--   API_PROVIDER = git_https_api
--   API_ALLOWED_PREFIXES = ('https://github.com/<YOUR-GH-ORG-OR-USER>')
--   API_USER_AUTHENTICATION = (TYPE = SNOWFLAKE_GITHUB_APP)
--   ENABLED = TRUE;
-- GRANT USAGE ON INTEGRATION GITHUB_INTEGRATION TO ROLE ACCOUNTADMIN;
