USE ROLE ACCOUNTADMIN;
USE WAREHOUSE WALMART_WH;
USE DATABASE WALMART_DEMO;
USE SCHEMA FORECAST;

CREATE STAGE IF NOT EXISTS RAW_STAGE
  DIRECTORY = (ENABLE = TRUE)
  COMMENT = 'Upload train.csv, stores.csv, features.csv here';

CREATE OR REPLACE FILE FORMAT CSV_FMT
  TYPE = CSV
  SKIP_HEADER = 1
  FIELD_DELIMITER = ','
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  NULL_IF = ('NA', '')
  EMPTY_FIELD_AS_NULL = TRUE
  TRIM_SPACE = TRUE;

CREATE OR REPLACE TABLE RAW_TRAIN (
    store NUMBER, dept NUMBER, week_date DATE, weekly_sales NUMBER(12,2), is_holiday BOOLEAN
);
CREATE OR REPLACE TABLE RAW_STORES (
    store NUMBER, type VARCHAR, size NUMBER
);
CREATE OR REPLACE TABLE RAW_FEATURES (
    store NUMBER, week_date DATE, temperature FLOAT, fuel_price FLOAT,
    markdown1 FLOAT, markdown2 FLOAT, markdown3 FLOAT, markdown4 FLOAT, markdown5 FLOAT,
    cpi FLOAT, unemployment FLOAT, is_holiday BOOLEAN
);

COPY INTO RAW_TRAIN    FROM @RAW_STAGE/train.csv    FILE_FORMAT=(FORMAT_NAME=CSV_FMT) ON_ERROR=ABORT_STATEMENT;
COPY INTO RAW_STORES   FROM @RAW_STAGE/stores.csv   FILE_FORMAT=(FORMAT_NAME=CSV_FMT) ON_ERROR=ABORT_STATEMENT;
COPY INTO RAW_FEATURES FROM @RAW_STAGE/features.csv FILE_FORMAT=(FORMAT_NAME=CSV_FMT) ON_ERROR=ABORT_STATEMENT;

-- Verify (expect 421570 / 45 / 8190 ; 143 weeks ; 2010-02-05..2012-10-26)
SELECT 'RAW_TRAIN' t, COUNT(*) rows FROM RAW_TRAIN
UNION ALL SELECT 'RAW_STORES', COUNT(*) FROM RAW_STORES
UNION ALL SELECT 'RAW_FEATURES', COUNT(*) FROM RAW_FEATURES;

/* Next: 02_build_analytics.sql */
